### ISSUE TITLE
Code 

### ISSUE THREAD

**Issue by torreyn** [Brackets-Themes/DarkSoda#5]
The text is read and highlighted in a light color when using the DarkSoda theme:

![screenshot 2015-03-16 14 19 54](https://cloud.githubusercontent.com/assets/665802/6676799/cdc76e08-cbe7-11e4-9009-2bcce8557953.png)

I forked DarkSoda theme and delete 3 CSS declaration in the code selector rule. I changed:

code {
    padding: 2px 4px;
    color: #d14;
    background-color: rgb(158, 158, 158);
    border: 1px solid rgb(122, 122, 122);
    white-space: nowrap;
}

to: 

code {
   padding: 2px 4px;
   white-space: nowrap;
}

And now it looks like:

![screenshot 2015-03-27 10 36 51](https://cloud.githubusercontent.com/assets/665802/6873394/35c969d8-d46d-11e4-8bb7-fedaca293def.png)

It would also look good if I left the `background-color: rgb(158, 158, 158);` rule

**Comment by MarcelGerber** [comment]
Fixed in v1.0.3 (6cbf9765157178614f9e2453a171d10df0e82475)
Closing.
